<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:46:31
define('MOD_CZ_ENABLED', true);
define('MOD_CZ_TITLE', 'cz Mojavi Module');
define('MOD_CZ_VERSION', 1.0);
define('MOD_CZ_NAME', 'cz');
define('MOD_CZ_AUTHOR', 'fly');
define('MOD_CZ_HOMEPAGE', null);
define('MOD_CZ_UPDATE_URL', null);
define('MOD_CZ_DESCRIPTION', 'cz Mojavi Module');
?>