<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:45:15
define('MOD_HANDLEORDER_ENABLED', true);
define('MOD_HANDLEORDER_TITLE', 'HandleOrder Mojavi Module');
define('MOD_HANDLEORDER_VERSION', 1.0);
define('MOD_HANDLEORDER_NAME', 'HandleOrder');
define('MOD_HANDLEORDER_AUTHOR', 'fly');
define('MOD_HANDLEORDER_HOMEPAGE', null);
define('MOD_HANDLEORDER_UPDATE_URL', null);
define('MOD_HANDLEORDER_DESCRIPTION', 'HandleOrder Mojavi Module');
?>