<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:46:40
define('MOD_MODIFYINFO_ENABLED', true);
define('MOD_MODIFYINFO_TITLE', 'ModifyInfo Mojavi Module');
define('MOD_MODIFYINFO_VERSION', 1.0);
define('MOD_MODIFYINFO_NAME', 'ModifyInfo');
define('MOD_MODIFYINFO_AUTHOR', 'fly');
define('MOD_MODIFYINFO_HOMEPAGE', null);
define('MOD_MODIFYINFO_UPDATE_URL', null);
define('MOD_MODIFYINFO_DESCRIPTION', 'ModifyInfo Mojavi Module');
?>