<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:47:01
define('MOD_CZC_ENABLED', true);
define('MOD_CZC_TITLE', 'czc Mojavi Module');
define('MOD_CZC_VERSION', 1.0);
define('MOD_CZC_NAME', 'czc');
define('MOD_CZC_AUTHOR', 'fly');
define('MOD_CZC_HOMEPAGE', null);
define('MOD_CZC_UPDATE_URL', null);
define('MOD_CZC_DESCRIPTION', 'czc Mojavi Module');
?>