<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:37
define('MOD_CERTIFIEDUSERLIST_ENABLED', true);
define('MOD_CERTIFIEDUSERLIST_TITLE', 'CertifiedUserList Mojavi Module');
define('MOD_CERTIFIEDUSERLIST_VERSION', 1.0);
define('MOD_CERTIFIEDUSERLIST_NAME', 'CertifiedUserList');
define('MOD_CERTIFIEDUSERLIST_AUTHOR', 'fly');
define('MOD_CERTIFIEDUSERLIST_HOMEPAGE', null);
define('MOD_CERTIFIEDUSERLIST_UPDATE_URL', null);
define('MOD_CERTIFIEDUSERLIST_DESCRIPTION', 'CertifiedUserList Mojavi Module');
?>