<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:28:15
define('MOD_CAIWU_ENABLED', true);
define('MOD_CAIWU_TITLE', 'CaiWu Mojavi Module');
define('MOD_CAIWU_VERSION', 1.0);
define('MOD_CAIWU_NAME', 'CaiWu');
define('MOD_CAIWU_AUTHOR', 'fly');
define('MOD_CAIWU_HOMEPAGE', null);
define('MOD_CAIWU_UPDATE_URL', null);
define('MOD_CAIWU_DESCRIPTION', 'CaiWu Mojavi Module');
?>