<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:08
define('MOD_ZBLOG_ENABLED', true);
define('MOD_ZBLOG_TITLE', 'zblog Mojavi Module');
define('MOD_ZBLOG_VERSION', 1.0);
define('MOD_ZBLOG_NAME', 'zblog');
define('MOD_ZBLOG_AUTHOR', 'fly');
define('MOD_ZBLOG_HOMEPAGE', null);
define('MOD_ZBLOG_UPDATE_URL', null);
define('MOD_ZBLOG_DESCRIPTION', 'zblog Mojavi Module');
?>