<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:03
define('MOD_FINANCELOG_ENABLED', true);
define('MOD_FINANCELOG_TITLE', 'dianpuRecord Mojavi Module');
define('MOD_FINANCELOG_VERSION', 1.0);
define('MOD_FINANCELOG_NAME', 'FinanceLog');
define('MOD_FINANCELOG_AUTHOR', 'fly');
define('MOD_FINANCELOG_HOMEPAGE', null);
define('MOD_FINANCELOG_UPDATE_URL', null);
define('MOD_FINANCELOG_DESCRIPTION', 'dianpuRecord Mojavi Module');
?>