<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:44:58
define('MOD_UPDATEPWD_ENABLED', true);
define('MOD_UPDATEPWD_TITLE', 'UpdatePwd Mojavi Module');
define('MOD_UPDATEPWD_VERSION', 1.0);
define('MOD_UPDATEPWD_NAME', 'UpdatePwd');
define('MOD_UPDATEPWD_AUTHOR', 'fly');
define('MOD_UPDATEPWD_HOMEPAGE', null);
define('MOD_UPDATEPWD_UPDATE_URL', null);
define('MOD_UPDATEPWD_DESCRIPTION', 'UpdatePwd Mojavi Module');
?>