<?php
// auth-generated by ModuleConfigHandler
// date: 01/13/2016 11:01:21
define('MOD_NOTICE_ENABLED', true);
define('MOD_NOTICE_TITLE', 'Notice Mojavi Module');
define('MOD_NOTICE_VERSION', 1.0);
define('MOD_NOTICE_NAME', 'Notice');
define('MOD_NOTICE_AUTHOR', 'fly');
define('MOD_NOTICE_HOMEPAGE', null);
define('MOD_NOTICE_UPDATE_URL', null);
define('MOD_NOTICE_DESCRIPTION', 'Notice Mojavi Module');
?>