<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:20:13
define('MOD_SALARY_ENABLED', true);
define('MOD_SALARY_TITLE', 'bumenjiang Mojavi Module');
define('MOD_SALARY_VERSION', 1.0);
define('MOD_SALARY_NAME', 'salary');
define('MOD_SALARY_AUTHOR', 'fly');
define('MOD_SALARY_HOMEPAGE', null);
define('MOD_SALARY_UPDATE_URL', null);
define('MOD_SALARY_DESCRIPTION', 'bumenjiang Mojavi Module');
?>