<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:44:59
define('MOD_MESSAGE_ENABLED', true);
define('MOD_MESSAGE_TITLE', 'Message Mojavi Module');
define('MOD_MESSAGE_VERSION', 1.0);
define('MOD_MESSAGE_NAME', 'Message');
define('MOD_MESSAGE_AUTHOR', 'fly');
define('MOD_MESSAGE_HOMEPAGE', null);
define('MOD_MESSAGE_UPDATE_URL', null);
define('MOD_MESSAGE_DESCRIPTION', 'Message Mojavi Module');
?>