<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:23
define('MOD_MENU_ENABLED', true);
define('MOD_MENU_TITLE', 'Menu Mojavi Module');
define('MOD_MENU_VERSION', 1.0);
define('MOD_MENU_NAME', 'Menu');
define('MOD_MENU_AUTHOR', 'fly');
define('MOD_MENU_HOMEPAGE', null);
define('MOD_MENU_UPDATE_URL', null);
define('MOD_MENU_DESCRIPTION', 'Menu Mojavi Module');
?>