<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:28:32
define('MOD_FENHONGJIANG_ENABLED', true);
define('MOD_FENHONGJIANG_TITLE', 'fenhongjiang Mojavi Module');
define('MOD_FENHONGJIANG_VERSION', 1.0);
define('MOD_FENHONGJIANG_NAME', 'fenhongjiang');
define('MOD_FENHONGJIANG_AUTHOR', 'fly');
define('MOD_FENHONGJIANG_HOMEPAGE', null);
define('MOD_FENHONGJIANG_UPDATE_URL', null);
define('MOD_FENHONGJIANG_DESCRIPTION', 'fenhongjiang Mojavi Module');
?>