<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:25
define('MOD_NEWSCLASS_ENABLED', true);
define('MOD_NEWSCLASS_TITLE', 'newsclass Mojavi Module');
define('MOD_NEWSCLASS_VERSION', 1.0);
define('MOD_NEWSCLASS_NAME', 'newsclass');
define('MOD_NEWSCLASS_AUTHOR', 'fly');
define('MOD_NEWSCLASS_HOMEPAGE', null);
define('MOD_NEWSCLASS_UPDATE_URL', null);
define('MOD_NEWSCLASS_DESCRIPTION', 'newsclass Mojavi Module');
?>