<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:45
define('MOD_PRODUCTTYPE_ENABLED', true);
define('MOD_PRODUCTTYPE_TITLE', 'ProductType Mojavi Module');
define('MOD_PRODUCTTYPE_VERSION', 1.0);
define('MOD_PRODUCTTYPE_NAME', 'ProductType');
define('MOD_PRODUCTTYPE_AUTHOR', 'fly');
define('MOD_PRODUCTTYPE_HOMEPAGE', null);
define('MOD_PRODUCTTYPE_UPDATE_URL', null);
define('MOD_PRODUCTTYPE_DESCRIPTION', 'ProductType Mojavi Module');
?>