<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:16
define('MOD_BACKUP_ENABLED', true);
define('MOD_BACKUP_TITLE', 'backup Mojavi Module');
define('MOD_BACKUP_VERSION', 1.0);
define('MOD_BACKUP_NAME', 'backup');
define('MOD_BACKUP_AUTHOR', 'fly');
define('MOD_BACKUP_HOMEPAGE', null);
define('MOD_BACKUP_UPDATE_URL', null);
define('MOD_BACKUP_DESCRIPTION', 'backup Mojavi Module');
?>