<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:18
define('MOD_KEFU_ENABLED', true);
define('MOD_KEFU_TITLE', 'kefu Mojavi Module');
define('MOD_KEFU_VERSION', 1.0);
define('MOD_KEFU_NAME', 'kefu');
define('MOD_KEFU_AUTHOR', 'fly');
define('MOD_KEFU_HOMEPAGE', null);
define('MOD_KEFU_UPDATE_URL', null);
define('MOD_KEFU_DESCRIPTION', 'kefu Mojavi Module');
?>