<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:24
define('MOD_GUANGGAO_ENABLED', true);
define('MOD_GUANGGAO_TITLE', 'guanggao Mojavi Module');
define('MOD_GUANGGAO_VERSION', 1.0);
define('MOD_GUANGGAO_NAME', 'guanggao');
define('MOD_GUANGGAO_AUTHOR', 'fly');
define('MOD_GUANGGAO_HOMEPAGE', null);
define('MOD_GUANGGAO_UPDATE_URL', null);
define('MOD_GUANGGAO_DESCRIPTION', 'guanggao Mojavi Module');
?>