<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:07:08
define('MOD_CHIZHI_ENABLED', true);
define('MOD_CHIZHI_TITLE', 'chizhi Mojavi Module');
define('MOD_CHIZHI_VERSION', 1.0);
define('MOD_CHIZHI_NAME', 'chizhi');
define('MOD_CHIZHI_AUTHOR', 'fly');
define('MOD_CHIZHI_HOMEPAGE', null);
define('MOD_CHIZHI_UPDATE_URL', null);
define('MOD_CHIZHI_DESCRIPTION', 'chizhi Mojavi Module');
?>