<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:02:37
define('MOD_RPRODUCT_ENABLED', true);
define('MOD_RPRODUCT_TITLE', 'RProduct Mojavi Module');
define('MOD_RPRODUCT_VERSION', 1.0);
define('MOD_RPRODUCT_NAME', 'RProduct');
define('MOD_RPRODUCT_AUTHOR', 'fly');
define('MOD_RPRODUCT_HOMEPAGE', null);
define('MOD_RPRODUCT_UPDATE_URL', null);
define('MOD_RPRODUCT_DESCRIPTION', 'RProduct Mojavi Module');
?>