<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:23
define('MOD_TOP_ENABLED', true);
define('MOD_TOP_TITLE', 'Top Mojavi Module');
define('MOD_TOP_VERSION', 1.0);
define('MOD_TOP_NAME', 'Top');
define('MOD_TOP_AUTHOR', 'fly');
define('MOD_TOP_HOMEPAGE', null);
define('MOD_TOP_UPDATE_URL', null);
define('MOD_TOP_DESCRIPTION', 'Top Mojavi Module');
?>