<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:41
define('MOD_WEIXIN_ENABLED', true);
define('MOD_WEIXIN_TITLE', 'weixin Mojavi Module');
define('MOD_WEIXIN_VERSION', 1.0);
define('MOD_WEIXIN_NAME', 'weixin');
define('MOD_WEIXIN_AUTHOR', 'fly');
define('MOD_WEIXIN_HOMEPAGE', null);
define('MOD_WEIXIN_UPDATE_URL', null);
define('MOD_WEIXIN_DESCRIPTION', 'weixin Mojavi Module');
?>