<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 16:13:46
define('MOD_PERMISSION_ENABLED', true);
define('MOD_PERMISSION_TITLE', 'permission Mojavi Module');
define('MOD_PERMISSION_VERSION', 1.0);
define('MOD_PERMISSION_NAME', 'permission');
define('MOD_PERMISSION_AUTHOR', 'fly');
define('MOD_PERMISSION_HOMEPAGE', null);
define('MOD_PERMISSION_UPDATE_URL', null);
define('MOD_PERMISSION_DESCRIPTION', 'permission Mojavi Module');
?>