<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:05
define('MOD_LOG_ENABLED', true);
define('MOD_LOG_TITLE', 'log Mojavi Module');
define('MOD_LOG_VERSION', 1.0);
define('MOD_LOG_NAME', 'log');
define('MOD_LOG_AUTHOR', 'fly');
define('MOD_LOG_HOMEPAGE', null);
define('MOD_LOG_UPDATE_URL', null);
define('MOD_LOG_DESCRIPTION', 'log Mojavi Module');
?>