<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:29:52
define('MOD_TIXIANMEMBER_ENABLED', true);
define('MOD_TIXIANMEMBER_TITLE', 'TiXiandanbao Mojavi Module');
define('MOD_TIXIANMEMBER_VERSION', 1.0);
define('MOD_TIXIANMEMBER_NAME', 'TiXianmember');
define('MOD_TIXIANMEMBER_AUTHOR', 'fly');
define('MOD_TIXIANMEMBER_HOMEPAGE', null);
define('MOD_TIXIANMEMBER_UPDATE_URL', null);
define('MOD_TIXIANMEMBER_DESCRIPTION', 'TiXiandanbao Mojavi Module');
?>