<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:45:24
define('MOD_NEWSLIST_ENABLED', true);
define('MOD_NEWSLIST_TITLE', 'newslist Mojavi Module');
define('MOD_NEWSLIST_VERSION', 1.0);
define('MOD_NEWSLIST_NAME', 'newslist');
define('MOD_NEWSLIST_AUTHOR', 'fly');
define('MOD_NEWSLIST_HOMEPAGE', null);
define('MOD_NEWSLIST_UPDATE_URL', null);
define('MOD_NEWSLIST_DESCRIPTION', 'newslist Mojavi Module');
?>