<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:49
define('MOD_QUERYNOTICE_ENABLED', true);
define('MOD_QUERYNOTICE_TITLE', 'QueryNotice Mojavi Module');
define('MOD_QUERYNOTICE_VERSION', 1.0);
define('MOD_QUERYNOTICE_NAME', 'QueryNotice');
define('MOD_QUERYNOTICE_AUTHOR', 'fly');
define('MOD_QUERYNOTICE_HOMEPAGE', null);
define('MOD_QUERYNOTICE_UPDATE_URL', null);
define('MOD_QUERYNOTICE_DESCRIPTION', 'QueryNotice Mojavi Module');
?>