<?php
// auth-generated by FilterConfigHandler
// date: 01/03/2016 01:41:18
require_once('/mnt/erp/public_html/csyingwu/webapp/filter/LoginFilter.class.php');
require_once('/mnt/erp/public_html/csyingwu/webapp/filter/ThdFilter.class.php');
require_once('/mnt/erp/public_html/csyingwu/webapp/filter/SedFilter.class.php');
$filters = array();
$filter = new ExecutionTimeFilter();
$filter->initialize($this->context, array('comment' => true));
$filters[] = $filter;
$filter = new LoginFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new ThdFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$filter = new SedFilter();
$filter->initialize($this->context, array('effect' => true));
$filters[] = $filter;
$list[$moduleName] =& $filters;
?>