<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:25:05
define('MOD_TUIJIAN_ENABLED', true);
define('MOD_TUIJIAN_TITLE', 'tuijian Mojavi Module');
define('MOD_TUIJIAN_VERSION', 1.0);
define('MOD_TUIJIAN_NAME', 'tuijian');
define('MOD_TUIJIAN_AUTHOR', 'fly');
define('MOD_TUIJIAN_HOMEPAGE', null);
define('MOD_TUIJIAN_UPDATE_URL', null);
define('MOD_TUIJIAN_DESCRIPTION', 'tuijian Mojavi Module');
?>