<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:41:18
define('MOD_ADMINLOGIN_ENABLED', true);
define('MOD_ADMINLOGIN_TITLE', 'AdminLogin Mojavi Module');
define('MOD_ADMINLOGIN_VERSION', 1.0);
define('MOD_ADMINLOGIN_NAME', 'AdminLogin');
define('MOD_ADMINLOGIN_AUTHOR', 'fly');
define('MOD_ADMINLOGIN_HOMEPAGE', null);
define('MOD_ADMINLOGIN_UPDATE_URL', null);
define('MOD_ADMINLOGIN_DESCRIPTION', 'AdminLogin Mojavi Module');
?>