<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:29:44
define('MOD_NOCHIZHI_ENABLED', true);
define('MOD_NOCHIZHI_TITLE', 'nochizhi Mojavi Module');
define('MOD_NOCHIZHI_VERSION', 1.0);
define('MOD_NOCHIZHI_NAME', 'nochizhi');
define('MOD_NOCHIZHI_AUTHOR', 'fly');
define('MOD_NOCHIZHI_HOMEPAGE', null);
define('MOD_NOCHIZHI_UPDATE_URL', null);
define('MOD_NOCHIZHI_DESCRIPTION', 'nochizhi Mojavi Module');
?>