<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:44:55
define('MOD_BOCHU_ENABLED', true);
define('MOD_BOCHU_TITLE', 'bochu Mojavi Module');
define('MOD_BOCHU_VERSION', 1.0);
define('MOD_BOCHU_NAME', 'bochu');
define('MOD_BOCHU_AUTHOR', 'fly');
define('MOD_BOCHU_HOMEPAGE', null);
define('MOD_BOCHU_UPDATE_URL', null);
define('MOD_BOCHU_DESCRIPTION', 'bochu Mojavi Module');
?>