<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 02:11:17
define('MOD_REGMEMBER_ENABLED', true);
define('MOD_REGMEMBER_TITLE', 'RegMember Mojavi Module');
define('MOD_REGMEMBER_VERSION', 1.0);
define('MOD_REGMEMBER_NAME', 'RegMember');
define('MOD_REGMEMBER_AUTHOR', 'fly');
define('MOD_REGMEMBER_HOMEPAGE', null);
define('MOD_REGMEMBER_UPDATE_URL', null);
define('MOD_REGMEMBER_DESCRIPTION', 'RegMember Mojavi Module');
?>