<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:42:21
define('MOD_TICKET_ENABLED', true);
define('MOD_TICKET_TITLE', 'ticket Mojavi Module');
define('MOD_TICKET_VERSION', 1.0);
define('MOD_TICKET_NAME', 'ticket');
define('MOD_TICKET_AUTHOR', 'fly');
define('MOD_TICKET_HOMEPAGE', null);
define('MOD_TICKET_UPDATE_URL', null);
define('MOD_TICKET_DESCRIPTION', 'ticket Mojavi Module');
?>