<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:45:14
define('MOD_CART_ENABLED', true);
define('MOD_CART_TITLE', 'cart Mojavi Module');
define('MOD_CART_VERSION', 1.0);
define('MOD_CART_NAME', 'cart');
define('MOD_CART_AUTHOR', 'fly');
define('MOD_CART_HOMEPAGE', null);
define('MOD_CART_UPDATE_URL', null);
define('MOD_CART_DESCRIPTION', 'cart Mojavi Module');
?>