<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:44:04
define('MOD_SHOP_ENABLED', true);
define('MOD_SHOP_TITLE', 'shop Mojavi Module');
define('MOD_SHOP_VERSION', 1.0);
define('MOD_SHOP_NAME', 'shop');
define('MOD_SHOP_AUTHOR', 'fly');
define('MOD_SHOP_HOMEPAGE', null);
define('MOD_SHOP_UPDATE_URL', null);
define('MOD_SHOP_DESCRIPTION', 'shop Mojavi Module');
?>