<?php
// auth-generated by ModuleConfigHandler
// date: 01/03/2016 01:43:53
define('MOD_CASH_ENABLED', true);
define('MOD_CASH_TITLE', 'Cash Mojavi Module');
define('MOD_CASH_VERSION', 1.0);
define('MOD_CASH_NAME', 'Cash');
define('MOD_CASH_AUTHOR', 'fly');
define('MOD_CASH_HOMEPAGE', null);
define('MOD_CASH_UPDATE_URL', null);
define('MOD_CASH_DESCRIPTION', 'Cash Mojavi Module');
?>